// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gcsystemmsgs.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION

#include "gcsystemmsgs.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

    const ::google::protobuf::EnumDescriptor *EGCSystemMsg_descriptor_ = NULL;
    const ::google::protobuf::EnumDescriptor *ESOMsg_descriptor_ = NULL;
    const ::google::protobuf::EnumDescriptor *EGCBaseClientMsg_descriptor_ = NULL;
    const ::google::protobuf::EnumDescriptor *EGCToGCMsg_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_gcsystemmsgs_2eproto() {
    protobuf_AddDesc_gcsystemmsgs_2eproto();
    const ::google::protobuf::FileDescriptor *file =
            ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
                    "gcsystemmsgs.proto");
    GOOGLE_CHECK(file != NULL);
    EGCSystemMsg_descriptor_ = file->enum_type(0);
    ESOMsg_descriptor_ = file->enum_type(1);
    EGCBaseClientMsg_descriptor_ = file->enum_type(2);
    EGCToGCMsg_descriptor_ = file->enum_type(3);
}

namespace {

    GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);

    inline void protobuf_AssignDescriptorsOnce() {
        ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                                           &protobuf_AssignDesc_gcsystemmsgs_2eproto);
    }

    void protobuf_RegisterTypes(const ::std::string &) {
        protobuf_AssignDescriptorsOnce();
    }

}  // namespace

void protobuf_ShutdownFile_gcsystemmsgs_2eproto() {
}

void protobuf_AddDesc_gcsystemmsgs_2eproto() {
    static bool already_here = false;
    if (already_here) return;
    already_here = true;
    GOOGLE_PROTOBUF_VERIFY_VERSION;

    ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
            "\n\022gcsystemmsgs.proto*\357\027\n\014EGCSystemMsg\022\023\n"
            "\017k_EGCMsgInvalid\020\000\022\021\n\rk_EGCMsgMulti\020\001\022\030\n"
            "\024k_EGCMsgGenericReply\020\n\022\026\n\022k_EGCMsgSyste"
            "mBase\0202\022\036\n\032k_EGCMsgAchievementAwarded\0203\022"
            "\026\n\022k_EGCMsgConCommand\0204\022\030\n\024k_EGCMsgStart"
            "Playing\0205\022\027\n\023k_EGCMsgStopPlaying\0206\022\033\n\027k_"
            "EGCMsgStartGameserver\0207\022\032\n\026k_EGCMsgStopG"
            "ameserver\0208\022\025\n\021k_EGCMsgWGRequest\0209\022\026\n\022k_"
            "EGCMsgWGResponse\020:\022\"\n\036k_EGCMsgGetUserGam"
            "eStatsSchema\020;\022*\n&k_EGCMsgGetUserGameSta"
            "tsSchemaResponse\020<\022\"\n\036k_EGCMsgGetUserSta"
            "tsDEPRECATED\020=\022 \n\034k_EGCMsgGetUserStatsRe"
            "sponse\020>\022\032\n\026k_EGCMsgAppInfoUpdated\020\?\022\033\n\027"
            "k_EGCMsgValidateSession\020@\022#\n\037k_EGCMsgVal"
            "idateSessionResponse\020A\022\"\n\036k_EGCMsgLookup"
            "AccountFromInput\020B\022\033\n\027k_EGCMsgSendHTTPRe"
            "quest\020C\022#\n\037k_EGCMsgSendHTTPRequestRespon"
            "se\020D\022\030\n\024k_EGCMsgPreTestSetup\020E\022\037\n\033k_EGCM"
            "sgRecordSupportAction\020F\022(\n$k_EGCMsgGetAc"
            "countDetails_DEPRECATED\020G\022\"\n\036k_EGCMsgRec"
            "eiveInterAppMessage\020I\022\030\n\024k_EGCMsgFindAcc"
            "ounts\020J\022\025\n\021k_EGCMsgPostAlert\020K\022\027\n\023k_EGCM"
            "sgGetLicenses\020L\022\030\n\024k_EGCMsgGetUserStats\020"
            "M\022\027\n\023k_EGCMsgGetCommands\020N\022\037\n\033k_EGCMsgGe"
            "tCommandsResponse\020O\022\032\n\026k_EGCMsgAddFreeLi"
            "cense\020P\022\"\n\036k_EGCMsgAddFreeLicenseRespons"
            "e\020Q\022\031\n\025k_EGCMsgGetIPLocation\020R\022!\n\035k_EGCM"
            "sgGetIPLocationResponse\020S\022\035\n\031k_EGCMsgSys"
            "temStatsSchema\020T\022\032\n\026k_EGCMsgGetSystemSta"
            "ts\020U\022\"\n\036k_EGCMsgGetSystemStatsResponse\020V"
            "\022\025\n\021k_EGCMsgSendEmail\020W\022\035\n\031k_EGCMsgSendE"
            "mailResponse\020X\022\034\n\030k_EGCMsgGetEmailTempla"
            "te\020Y\022$\n k_EGCMsgGetEmailTemplateResponse"
            "\020Z\022\032\n\026k_EGCMsgGrantGuestPass\020[\022\"\n\036k_EGCM"
            "sgGrantGuestPassResponse\020\\\022\035\n\031k_EGCMsgGe"
            "tAccountDetails\020]\022%\n!k_EGCMsgGetAccountD"
            "etailsResponse\020^\022\033\n\027k_EGCMsgGetPersonaNa"
            "mes\020_\022#\n\037k_EGCMsgGetPersonaNamesResponse"
            "\020`\022\030\n\024k_EGCMsgMultiplexMsg\020a\022$\n k_EGCMsg"
            "WebAPIRegisterInterfaces\020e\022\034\n\030k_EGCMsgWe"
            "bAPIJobRequest\020f\022(\n$k_EGCMsgWebAPIJobReq"
            "uestHttpResponse\020h\022+\n\'k_EGCMsgWebAPIJobR"
            "equestForwardResponse\020i\022\031\n\024k_EGCMsgMemCa"
            "chedGet\020\310\001\022!\n\034k_EGCMsgMemCachedGetRespon"
            "se\020\311\001\022\031\n\024k_EGCMsgMemCachedSet\020\312\001\022\034\n\027k_EG"
            "CMsgMemCachedDelete\020\313\001\022\033\n\026k_EGCMsgMemCac"
            "hedStats\020\314\001\022#\n\036k_EGCMsgMemCachedStatsRes"
            "ponse\020\315\001\022\025\n\020k_EGCMsgSQLStats\020\322\001\022\035\n\030k_EGC"
            "MsgSQLStatsResponse\020\323\001\022\037\n\032k_EGCMsgMaster"
            "SetDirectory\020\334\001\022\'\n\"k_EGCMsgMasterSetDire"
            "ctoryResponse\020\335\001\022#\n\036k_EGCMsgMasterSetWeb"
            "APIRouting\020\336\001\022+\n&k_EGCMsgMasterSetWebAPI"
            "RoutingResponse\020\337\001\022&\n!k_EGCMsgMasterSetC"
            "lientMsgRouting\020\340\001\022.\n)k_EGCMsgMasterSetC"
            "lientMsgRoutingResponse\020\341\001\022\027\n\022k_EGCMsgSe"
            "tOptions\020\342\001\022\037\n\032k_EGCMsgSetOptionsRespons"
            "e\020\343\001\022\030\n\023k_EGCMsgSystemBase2\020\364\003\022#\n\036k_EGCM"
            "sgGetPurchaseTrustStatus\020\365\003\022+\n&k_EGCMsgG"
            "etPurchaseTrustStatusResponse\020\366\003\022\032\n\025k_EG"
            "CMsgUpdateSession\020\367\003\022%\n k_EGCMsgGCAccoun"
            "tVacStatusChange\020\370\003\022\034\n\027k_EGCMsgCheckFrie"
            "ndship\020\371\003\022$\n\037k_EGCMsgCheckFriendshipResp"
            "onse\020\372\003\022\"\n\035k_EGCMsgGetPartnerAccountLink"
            "\020\373\003\022*\n%k_EGCMsgGetPartnerAccountLinkResp"
            "onse\020\374\003\022)\n$k_EGCMsgVSReportedSuspiciousA"
            "ctivity\020\375\003\022(\n#k_EGCMsgAccountTradeBanSta"
            "tusChange\020\376\003\022$\n\037k_EGCMsgAccountLockStatu"
            "sChange\020\377\003\022\037\n\032k_EGCMsgDPPartnerMicroTxns"
            "\020\200\004\022\'\n\"k_EGCMsgDPPartnerMicroTxnsRespons"
            "e\020\201\004\022\025\n\020k_EGCMsgGetIPASN\020\202\004\022\035\n\030k_EGCMsgG"
            "etIPASNResponse\020\203\004\022\036\n\031k_EGCMsgGetAppFrie"
            "ndsList\020\204\004\022&\n!k_EGCMsgGetAppFriendsListR"
            "esponse\020\205\004\022\"\n\035k_EGCMsgVacVerificationCha"
            "nge\020\206\004\022%\n k_EGCMsgAccountPhoneNumberChan"
            "ge\020\207\004\022#\n\036k_EGCMsgAccountTwoFactorChange\020"
            "\210\004\022 \n\033k_EGCMsgCheckClanMembership\020\211\004\022(\n#"
            "k_EGCMsgCheckClanMembershipResponse\020\212\004*\225"
            "\002\n\006ESOMsg\022\023\n\017k_ESOMsg_Create\020\025\022\023\n\017k_ESOM"
            "sg_Update\020\026\022\024\n\020k_ESOMsg_Destroy\020\027\022\034\n\030k_E"
            "SOMsg_CacheSubscribed\020\030\022\036\n\032k_ESOMsg_Cach"
            "eUnsubscribed\020\031\022\033\n\027k_ESOMsg_UpdateMultip"
            "le\020\032\022#\n\037k_ESOMsg_CacheSubscriptionCheck\020"
            "\033\022%\n!k_ESOMsg_CacheSubscriptionRefresh\020\034"
            "\022$\n k_ESOMsg_CacheSubscribedUpToDate\020\035*\353"
            "\001\n\020EGCBaseClientMsg\022\030\n\023k_EMsgGCPingReque"
            "st\020\271\027\022\031\n\024k_EMsgGCPingResponse\020\272\027\022\032\n\025k_EM"
            "sgGCClientWelcome\020\244\037\022\032\n\025k_EMsgGCServerWe"
            "lcome\020\245\037\022\030\n\023k_EMsgGCClientHello\020\246\037\022\030\n\023k_"
            "EMsgGCServerHello\020\247\037\022\032\n\025k_EMsgGCClientGo"
            "odbye\020\250\037\022\032\n\025k_EMsgGCServerGoodbye\020\251\037*\354\002\n"
            "\nEGCToGCMsg\022\032\n\025k_EGCToGCMsgMasterAck\020\226\001\022"
            "\"\n\035k_EGCToGCMsgMasterAckResponse\020\227\001\022\027\n\022k"
            "_EGCToGCMsgRouted\020\230\001\022\034\n\027k_EGCToGCMsgRout"
            "edReply\020\231\001\022#\n\036k_EMsgGCUpdateSubGCSession"
            "Info\020\232\001\022$\n\037k_EMsgGCRequestSubGCSessionIn"
            "fo\020\233\001\022,\n\'k_EMsgGCRequestSubGCSessionInfo"
            "Response\020\234\001\022&\n!k_EGCToGCMsgMasterStartup"
            "Complete\020\235\001\022!\n\034k_EMsgGCToGCSOCacheSubscr"
            "ibe\020\236\001\022#\n\036k_EMsgGCToGCSOCacheUnsubscribe"
            "\020\237\001B\005H\001\200\001\000", 3970);
    ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
            "gcsystemmsgs.proto", &protobuf_RegisterTypes);
    ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_gcsystemmsgs_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_gcsystemmsgs_2eproto {
    StaticDescriptorInitializer_gcsystemmsgs_2eproto() {
        protobuf_AddDesc_gcsystemmsgs_2eproto();
    }
} static_descriptor_initializer_gcsystemmsgs_2eproto_;

const ::google::protobuf::EnumDescriptor *EGCSystemMsg_descriptor() {
    protobuf_AssignDescriptorsOnce();
    return EGCSystemMsg_descriptor_;
}

bool EGCSystemMsg_IsValid(int value) {
    switch (value) {
        case 0:
        case 1:
        case 10:
        case 50:
        case 51:
        case 52:
        case 53:
        case 54:
        case 55:
        case 56:
        case 57:
        case 58:
        case 59:
        case 60:
        case 61:
        case 62:
        case 63:
        case 64:
        case 65:
        case 66:
        case 67:
        case 68:
        case 69:
        case 70:
        case 71:
        case 73:
        case 74:
        case 75:
        case 76:
        case 77:
        case 78:
        case 79:
        case 80:
        case 81:
        case 82:
        case 83:
        case 84:
        case 85:
        case 86:
        case 87:
        case 88:
        case 89:
        case 90:
        case 91:
        case 92:
        case 93:
        case 94:
        case 95:
        case 96:
        case 97:
        case 101:
        case 102:
        case 104:
        case 105:
        case 200:
        case 201:
        case 202:
        case 203:
        case 204:
        case 205:
        case 210:
        case 211:
        case 220:
        case 221:
        case 222:
        case 223:
        case 224:
        case 225:
        case 226:
        case 227:
        case 500:
        case 501:
        case 502:
        case 503:
        case 504:
        case 505:
        case 506:
        case 507:
        case 508:
        case 509:
        case 510:
        case 511:
        case 512:
        case 513:
        case 514:
        case 515:
        case 516:
        case 517:
        case 518:
        case 519:
        case 520:
        case 521:
        case 522:
            return true;
        default:
            return false;
    }
}

const ::google::protobuf::EnumDescriptor *ESOMsg_descriptor() {
    protobuf_AssignDescriptorsOnce();
    return ESOMsg_descriptor_;
}

bool ESOMsg_IsValid(int value) {
    switch (value) {
        case 21:
        case 22:
        case 23:
        case 24:
        case 25:
        case 26:
        case 27:
        case 28:
        case 29:
            return true;
        default:
            return false;
    }
}

const ::google::protobuf::EnumDescriptor *EGCBaseClientMsg_descriptor() {
    protobuf_AssignDescriptorsOnce();
    return EGCBaseClientMsg_descriptor_;
}

bool EGCBaseClientMsg_IsValid(int value) {
    switch (value) {
        case 3001:
        case 3002:
        case 4004:
        case 4005:
        case 4006:
        case 4007:
        case 4008:
        case 4009:
            return true;
        default:
            return false;
    }
}

const ::google::protobuf::EnumDescriptor *EGCToGCMsg_descriptor() {
    protobuf_AssignDescriptorsOnce();
    return EGCToGCMsg_descriptor_;
}

bool EGCToGCMsg_IsValid(int value) {
    switch (value) {
        case 150:
        case 151:
        case 152:
        case 153:
        case 154:
        case 155:
        case 156:
        case 157:
        case 158:
        case 159:
            return true;
        default:
            return false;
    }
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
