
#define SOURCEENGINEREBUILD_NAME "Source Engine Rebuild"
#define SOURCEENGINEREBUILD_VERSION_TEXT "0.1.6"
#define SOURCEENGINEREBUILD_VERSION_MAJOR 0
#define SOURCEENGINEREBUILD_VERSION_MINOR 1
#define SOURCEENGINEREBUILD_VERSION_BUILD 6
#define SOURCEENGINEREBUILD_VERSION Version(SOURCEENGINEREBUILD_VERSION_MAJOR, SOURCEENGINEREBUILD_VERSION_MINOR, SOURCEENGINEREBUILD_VERSION_BUILD)
#define SOURCEENGINEREBUILD_COMPANY "KaoruXun"
#define SOURCEENGINEREBUILD_COPYRIGHT "Copyright (c) 2019-2021 KaoruXun. All rights reserved."

int source_build_number(void);