#include "shaderlib/cshader.h"

class splinerope_vs20_Static_Index {
public:
    splinerope_vs20_Static_Index() {
    }

    int GetIndex() {
        // Asserts to make sure that we aren't using any skipped combinations.
        // Asserts to make sure that we are setting all of the combination vars.
#ifdef _DEBUG
#endif // _DEBUG
        return 0;
    }
};

#define shaderStaticTest_splinerope_vs20 0

class splinerope_vs20_Dynamic_Index {
public:
    splinerope_vs20_Dynamic_Index() {
    }

    int GetIndex() {
        // Asserts to make sure that we aren't using any skipped combinations.
        // Asserts to make sure that we are setting all of the combination vars.
#ifdef _DEBUG
#endif // _DEBUG
        return 0;
    }
};

#define shaderDynamicTest_splinerope_vs20 0
